config/routes.rb
Rails.application.routes.draw do
  get 'carts/show'

  devise_for :users, path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  resources :items
  resource :cart, only: [:show] do
    put 'add/:item_id', to: 'carts#add', as: :add_to
    put 'remove/:item_id', to: 'carts#remove', as: :remove_from
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'items#index'

  get 'techtac', to: 'main#techtac'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  def cart_action(current_user_id)
    if $redis.sismember "cart#{current_user_id}", id
      "Remove from"
    else
      "Add to"
    end
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   def cart_count
     $redis.scard "cart#{id}"
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!

  def show
    cart_ids = $redis.smembers current_user_cart
    @cart_items = Item.find(cart_ids)
  end

  def add
    $redis.sadd current_user_cart, params[:item_id]
    render json: current_user.cart_count, status: 200
  end

  def remove
    $redis.srem current_user_cart, params[:item_id]
    render json: current_user.cart_count, status: 200
  end

  private

  def current_user_cart
    "cart#{current_user.id}"
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
    @item = Item.find(params[:id])
    @cart_action = @item.cart_action current_user.try :id
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :price, :description, :image, :image2, :image3, :image4)
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def techtac

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/carts/show.html.erb
<div id="mycart" class="">
  <div class="p1 glassy-bg mb1 text-center radius-l1 radius-r1">
    <h4>My Cart</h4>
    <p class="mb0"> You've selected <span class="cart-count"><%=current_user.cart_count%></span> items!</p>
  </div>

  <% @cart_items.each do |item|%>
  <div data-equalizer class="cart-movie large-12 column mb1">
    <div class="column large-2 text-center p0" data-equalizer-watch>
      <%=link_to item do%>
        <%=image_tag item.image, class: "img img-thumbnail img-custom"%>
      <%end%>
    </div>
    <div class="column large-7 glassy-bg text-center" data-equalizer-watch>
        <p class="scale ptm"> <%= item.title %> </p>
    </div>
    <div class="column large-3 primary-bg text-center radius-r1" data-equalizer-watch>
      <%=link_to "" , data: {targetUrl: remove_from_cart_path(item)} do%>
        <i class="fi-x right"></i>
      <%end%>
      <h4 class="scale">$ <%= item.price %></h4>
    </div>
  </div>
  <%end%>
</div>

app/views/items/_catalog.html.erb
<div class="container">
  <ul class="row" id="products">
    <% @items.each do |item| %>
      <li class="col-lg-4 col-md-6 col-sm-12">
        <div class="">
          <%= link_to item, class: "btn" do %>
            <%= image_tag("#{item.image}.jpg", :alt => "tubing anchor catcher", :class => "img img-thumbnail") %>
          <% end %>
          <div class="item-info" align="center">
            <div class="title">
              <h5><%= item.title %></h5>
            </div>
            <p class="">$ <%= item.price %></p>
          </div>
        </div>
      </li>
    <% end %>
  </ul>
</div>

<%= link_to 'New Product', new_item_path %>

app/views/items/_form.html.erb
<%= form_for(item) do |f| %>
  <% if item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>

      <ul>
      <% item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :image %>
    <%= f.text_field :image %>
  </div>

  <div class="field">
    <%= f.label :image2 %>
    <%= f.text_field :image2 %>
  </div>

  <div class="field">
    <%= f.label :image3 %>
    <%= f.text_field :image3 %>
  </div>

  <div class="field">
    <%= f.label :image4 %>
    <%= f.text_field :image4 %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<h2 align="center">Products</h2>

<h5 align="center"><%= link_to "Slimline TACs", "#" %> | <%= link_to "Standard TACs", "#" %></h5>

<%= render 'items/catalog' %>





<h1>Items</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Price</th>
      <th>Description</th>
      <th>Image</th>
      <th>Image2</th>
      <th>Image3</th>
      <th>Image4</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td><%= item.price %></td>
        <td><%= item.description %></td>
        <td><%= item.image %></td>
        <td><%= item.image2 %></td>
        <td><%= item.image3 %></td>
        <td><%= item.image4 %></td>
        <td><%= link_to 'Show', item %></td>
        <td><%= link_to 'Edit', edit_item_path(item) %></td>
        <td><%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Item', new_item_path %>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<div>
  <h3><%= @item.title %></h3>
  <%= image_tag("#{@item.image}.jpg", :alt => "tubing anchor catcher", :class => "img-custom img-thumbnail") %>

  <div class="row">
  <a class="fancybox" rel="group" href="<%= asset_path("#{@item.image2}.jpg") %>">
    <img id="fancy" class="col-lg-4" src="<%= asset_path("#{@item.image2}.jpg") %>" alt="" />
  </a>
  <a class="fancybox" rel="group" href="<%= asset_path("#{@item.image3}.jpg") %>">
    <img id="fancy" class="col-lg-4" src="<%= asset_path("#{@item.image3}.jpg") %>" alt="" />
  </a>
  <a class="fancybox" rel="group" href="<%= asset_path("#{@item.image4}.jpg") %>">
    <img id="fancy" class="col-lg-4" src="<%= asset_path("#{@item.image4}.jpg") %>" alt="" />
  </a>
</div>

  <h4>$<%= @item.price %></h4>
  <p><%= @item.description %></p>
</div>


<div align="center">
  <%= link_to 'Back', items_path %>
</div>

<%if signed_in?%>
  <%=link_to "", class: "btn btn-lg", data: {target: @cart_action, addUrl: add_to_cart_path(@item), removeUrl: remove_from_cart_path(@item)} do%>
    <i class="glyphicon glyphicon-shopping-cart"></i>
    <span><%=@cart_action%></span> Cart
  <%end%>
<%end%>
<br />
<br />
<br />


<script>
$(document).ready(function() {
  $("a.fancybox").fancybox();
});
</script>

app/views/layouts/_alerts.html.erb
<%if notice.present? || alert.present? %>
  <div class="row" align="center">
    <%is_alert = alert.present? ? "alert" : ""%>
      <div data-alert class="alert-box <%=is_alert%>">
        <%=notice || alert%>
        <a href="#" class="close">&times;</a>
      </div>
  </div>
<%end%>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Rocket Oil Supply", root_path, class: "navbar-brand", id: "logo" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav" id="nav-item">
        <li><%= link_to "Tech TAC Anchors", techtac_path %></li>
        <li><a href="#">The Rocket Advantage</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Products <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "All Products", root_path %></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" id="nav-item">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right" id="nav-item">
      <% if signed_in? %>
      <li>
        <%= link_to cart_path do%>
          <i class="glyphicon glyphicon-shopping-cart"></i>
          My Cart
          (<span class="cart-count"><%=current_user.cart_count%></span>)
        <%end%>
      </li>
        <li><%= link_to current_user.email, edit_user_registration_path %></li>
        <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
      <% else %>
        <li><%= link_to "Register", new_user_registration_path %></li>
        <li><%= link_to "Login", new_user_session_path %></li>
      <% end %>

        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">

            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rocket Oil Supplies</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/nav' %>
    <div class="container">
      <%= render "layouts/alerts" %>
    </div>
    <div class="container">
      <%= yield %>
    </div>

    
  </body>
</html>

app/views/main/techtac.html.erb
<div class="center jumbotron" id="jumbo">
  <h2>Rocket Oil Supplies is a proud supplier of Tech TAC Slimline TACs</h2>
  <p>Slimline TACs are only available to certified Tech TAC dealers.</p>
  <%= link_to "Contact Tech TAC dealers", "#", class: "btn btn-primary btn-lg" %>
  <%= link_to "Become a dealer", "#", class: "btn btn-primary btn-lg" %>
</div>

<br />
<br />

<div class="main">
  <h3>Advantages of Slimline</h3>
  <p>Tech TAC’s patented Slimline Tubing Anchor Catcher provides all the benefits of a standard tubing anchor catcher, while improving well efficiencies. Among the many benefits of the Slimline TAC is the smaller diameter and tapered flow deflectors.</p>

<br />

  <p>The patent protected Slimline TAC is able to greatly increase well production and decrease down time. Flow capacity is increased beyond what is provided by a standard TAC for the following reasons </p>
  <ul>
    <li>1. Smaller Overall Diameter</li>
    <li>2. Tapered Flow Deflectors</li>
  </ul>

<br />

  <p>Due to the smaller overall diameter, our Slimline TACs provide less restriction in the well, which allows natural gas to break out easier and makes the pump less likely to gas lock. A standard size tubing anchor, being closer to the size of the casing, restricts the natural gas flow up the annulus.

Located on top and bottom of the TAC, our flow deflectors reduce flow turbulence as well as reduce the lip where dirt and debris can build up, making the well operate more efficiently.

In worst-case scenarios, it may be necessary to cut over or mill up a TAC.  Our Slimline TAC is able to fit inside a shoe mill, which significantly reduces cutver time.</p>

<p>Benefits of the Slimline TAC include:</p>
<ul>
  <li>Overall reduced diameter from standard TAC</li>
  <li>Increased flow through the annulus</li>
  <li>Reduced area for debris collection</li>
  <li>Reduced gas locking</li>
  <li>Top and bottom flow subs to reduce flow turbulence</li>
  <li>Option to set in or below perforations</li>
  <li>Fits inside a mill shoe</li>
  <li>Dramatically decreases cut over time</li>
</ul>



</div>